### ISSUE TITLE
CouchDB service

### ISSUE THREAD

**Issue by andreacampi** [cloudfoundry-attic/vcap-services#11]

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
