### ISSUE TITLE
More docs 

### ISSUE THREAD

**Issue by lgs** [cloudfoundry-attic/vcap-services#16]
Should be great to have more docs for beginners, at least a README, better some per service dedicated wikies. For example I really miss a starting point to GO for ElasticSearch new service.

Keep on the great job
Luca

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
