### ISSUE TITLE
Documentation on how to run the tests

### ISSUE THREAD

**Issue by jduff** [cloudfoundry-attic/vcap-services#4]
I'm trying to run the tests for each of the services and all of them are failing with

```
Could not connect to server on nats://localhost:4222
```

What is supposed to be running there for these to work?

**Comment by kushmerick** [comment]
This bug has been fixed: https://github.com/cloudfoundry/vcap-services/commit/f25d821ec01106f23735332aecdaaac4f637729b

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>
