### ISSUE TITLE
Add Elastic Search as a cloudfoundry service

### ISSUE THREAD

**Issue by dadoonet** [cloudfoundry-attic/vcap-services#7]
It would be a nice feature to have Elastic Search available as a standard Search Service in cloud foundry.

ES project is here : www.elasticsearch.org
I don't know at this time how to do it, as I'm just starting with cloudfoundry. ;-)

**Comment by jorgeu** [comment]
this would be really nice

**Comment by seigel** [comment]
+1

**Comment by camechis** [comment]
+1

**Comment by benjaminbarbe** [comment]
+1

**Comment by ghost** [comment]
Agree!

**Comment by seigel** [comment]
+1

**Comment by splix** [comment]
+1

**Comment by lgs** [comment]
+1

**Comment by rkoster** [comment]
+1

**Comment by mente** [comment]
+1

**Comment by andreiz** [comment]
+1

**Comment by farrelley** [comment]
+1

**Comment by nickdunn** [comment]
+1

**Comment by mjpowersjr** [comment]
+1

**Comment by gavinhogan** [comment]
+1

**Comment by altfatterz** [comment]
+1

**Comment by mpccolorado** [comment]
+10

**Comment by dgouyette** [comment]
+1

**Comment by frhwang** [comment]
I have finished implementing **Elasticsearch as a Service** initial version and pushing it to Cloud Foundry Gerrit repository. Currently, waiting for reviews. Related issues are following:
- http://reviews.cloudfoundry.org/5612
- http://reviews.cloudfoundry.org/5613

**Comment by medcl** [comment]
cool!

**Comment by lgs** [comment]
@frhwang 

should be great, but until now I just get a `Not Found` page @ mentioned links ...

**Comment by frhwang** [comment]
@lgs 
If you are not signed in http://reviews.cloudfoundry.org, you'll get a `Not found` page. Please sign in.

**Comment by lgs** [comment]
thz I'm in, 

I'm really new to cloudfoundry, ... I think I'll need to have look around

**Comment by vmware-ac-gerrit** [comment]
Dear Cloud Foundry contributor,

<p>
Thank you for your interest in Cloud Foundry. We are tracking issues in Jira at https://cloudfoundry.atlassian.net/secure/Dashboard.jspa. Please submit your issue in Jira and we will attend to it as soon as we can.
</p>


<p>
Best Regards,<br/>
Cloud Foundry Team
</p>

**Comment by dadoonet** [comment]
For information for all followers, feature request is here : https://cloudfoundry.atlassian.net/browse/CF-47

**Comment by amrangan** [comment]
Is this project being actively worked on ?
If not, can you please specify the reason for closing it ?
We are evaluating ElasticSearch for our application and we use CloudFoundry.

**Comment by shalako** [comment]
Elastic Search has been moved to the Service Community Contrib repo
https://github.com/cloudfoundry/cf-services-contrib/tree/master/elasticsearch

This service, like the rest of the code in the contrib repo, is not currently maintained by the Cloud Foundry core team and we make no claims as to its functionality. The community is welcome to enhance it.

**Comment by NathanHazout** [comment]
This is an old issue. Can someone tell me what happened? All the links here seem dead...
I'm looking to deploy elasticsearch to a cloud foundry instance.

**Comment by shalako** [comment]
Hello,

See https://github.com/cloudfoundry-community/cf-services-contrib-release

Note that these legacy services depend on an integration that is no longer supported. 

I recommend posting to cf-dev@lists.cloudfoundry.org, asking whether there is a current OSS BOSH release for ELK.
